spring:
  config:
    import: application-secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

jwt:
  secret: ${JWT.SECRET}
  ACCESS_TOKEN_EXPIRED: 72000000
  REFRESH_TOKEN_EXPIRED: 1209600000
  KAKAO_CLIENT_ID: ${KAKAO.CLIENT_ID}
  KAKAO_REDIRECT_URI: ${KAKAO.REDIRECT_URI}